services:
  mysql:
    image: mysql:latest
    container_name: mysql-inventory-service
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: inventory-service
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-inventory-data:/var/lib/mysql
volumes:
  mysql-inventory-data:
